# docker-compose isn't used by Fly, but can be used for doing quick dev checks of the Dockerfile setup

version: "3"
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: test
        RUBY_VERSION: 2.7.3
        PG_VERSION: 12
        NODE_VERSION: 14
        BUNDLER_VERSION: 2.2.19
    entrypoint: ["/rails/bin/docker-compose-entrypoint"]
    command: "rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/rails:cached
      - rails_cache:/rails/tmp/cache
      - packs:/rails/public/packs
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/
      DB_HOST: postgres
      DB_USER: stimulusreflexcom
      DB_PASSWORD: stimulusreflexcom
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stimulusreflexcom_development
      POSTGRES_USER: stimulusreflexcom
      POSTGRES_PASSWORD: stimulusreflexcom
    ports:
      - "5432"
    healthcheck:
      test: pg_isready -U stimulusreflexcom -d stimulusreflexcom_development -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis:/data
    ports:
      - "6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
  rails_cache:
  packs:
