default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", nil) %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", nil) %>
  password: <%= ENV.fetch("DB_PASSWORD", nil) %>

development:
  <<: *default
  database: stimulusreflexcom_development

test:
  <<: *default
  database: stimulusreflexcom_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
