production: &production
  url: <%= "redis://#{ENV['FLY_REGION']}.#{ENV['REDIS_HOST']}/1" %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379/1") %>
  timeout: 1

test:
  <<: *development
